platform :ios, '15.1'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static
end

project 'iosApp', {
  'Debug' => :debug,
  'Beta' => :release,
  'Release' => :release
}

target 'iosApp' do
  pod 'ComposeApp', :path => '../composeApp'

  target 'share' do
    inherit! :search_paths
    pod 'ComposeApp', path: '../composeApp'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      unless xcconfig.include?('#include "../../../Versions.xcconfig"')
        new_xcconfig = "#include \"../../../Versions.xcconfig\"\n\n" + xcconfig
        File.write(xcconfig_path, new_xcconfig)
      end
    end
  end
end
